name: Deploy to Hugging Face

on:
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types: [completed]
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.event.workflow_run.head_branch || 'main' }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN || '' }}
      HF_SPACE_URL: ${{ secrets.HF_SPACE_URL || '' }}

    # déploie seulement si la CI est "success" ET si les secrets existent
    if: ${{ github.event.workflow_run.conclusion == 'success' && env.HF_TOKEN != '' && env.HF_SPACE_URL != '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.HF_GIT_EMAIL || 'actions@github.com' }}"
          git config --global user.name  "${{ secrets.HF_GIT_NAME  || 'github-actions' }}"
          git lfs install

      - name: Push to Space
        run: |
          SPACE_URL_AUTH=$(echo "$HF_SPACE_URL" | sed "s#https://#https://user:${HF_TOKEN}@#")
          git remote add space "$SPACE_URL_AUTH" || git remote set-url space "$SPACE_URL_AUTH"
          git push space HEAD:main --force
